### ISSUE TITLE
Problem with mysql?

### ISSUE THREAD

**Issue by lewpio** [ArqTras/nodejs-pool#1]
Hi,

While running install script i'm getting such error:

Unhandled rejection Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'pool'                  @'localhost' (using password: YES)

**Comment by ArqTras** [comment]
Witch coin installer ?

**Comment by lewpio** [comment]
Well, it did not ask for any coin.
I see that there is issue in etn installer - 
mysql -u root --password=$ROOT_SQL_PASS < deployment/base.sql  - no such file as base.sql

**Comment by ArqTras** [comment]
Corrected and uploaded thanks

**Comment by lewpio** [comment]
Found another problem:

Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for resolvconf (1.78ubuntu6) ...
Processing triggers for ca-certificates (20170717~16.04.1) ...
Updating certificates in /etc/ssl/certs...
17 added, 42 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
bash: line 20: unexpected EOF while looking for matching `"'
bash: line 21: syntax error: unexpected end of file
