### ISSUE TITLE
Open

### ISSUE THREAD

**Issue by ArqTras** [ArqTras/nodejs-pool#1]
Please put here info about bugs and solutions.

**Comment by bobbieltd** [comment]
At this pool hash rate, we got to wait so long to test the first block. I thought it would be fast because Electroneum was new coin.  Is there Electrineum testnet ?

**Comment by ArqTras** [comment]
It is and it seems that everything works. The current version should also work correctly

**Comment by bobbieltd** [comment]
What do you think about buying hashing power from NiceHash ? How much should I pay for NiceHash to make it quicker ? Does this pool work with NiceHash ?

**Comment by ArqTras** [comment]
Not profitable 
Wait to first block You will get almost all reward

**Comment by ArqTras** [comment]
Corrected few things in mysql and deploy

**Comment by bobbieltd** [comment]
To update mysql (I saw you remove space at ports value), do I have to stop all api and start again after mysql database update ?
pm2 stop blockManager worker payments remoteShare longRunner api
pm2 start blockManager worker payments remoteShare longRunner api
Thanks.

**Comment by ArqTras** [comment]
Check in your pool database or admin section wallet port and daemon port, must by without spaces

**Comment by ArqTras** [comment]
Should work without issues
