### ISSUE TITLE
Shares rejected mining sumo

### ISSUE THREAD

**Issue by TheSquiffy** [ArqTras/nodejs-pool#10]
Hi, I setup the mining pool with sumo deployment script. Everything went good.

Testing with xmr-stak I always get rejected shares. If I change miner algorithm from sumokoin to graft (yes, mining graft against sumo pool) I get accepted shares instead, weird...

Miner works well with other sumo pools.

**Comment by Ossii** [comment]
Have you upgraded config to work with cryptonight_heavy ? since sumo forked to new PoW

**Comment by TheSquiffy** [comment]
hi, I set **cryptonight_heavy**, nothing changed, still rejected.

![immagine](https://user-images.githubusercontent.com/22369885/39333579-b0d529f8-49ab-11e8-8472-8de968bd61d7.png)

any clue?

**Comment by Ossii** [comment]
Poolside, have you updated there?

Changes needed:
package.json
    "multi-hashing": "git://github.com/quangvu3/node-multi-hashing.git#Nan-2.0"

lib/coins/sumo.js
    this.cryptoNight = multiHashing.cryptonight_heavy;

**Comment by TheSquiffy** [comment]
ohh it works! Thank you!

for the records, after changing the code, I had to refresh packages:

```
npm i -g npm-check-updates
ncu -u
npm install
```

**Comment by Ossii** [comment]
indeed, can also rm -rf node_modules and do npm install after.
Good you got it working :)
