### ISSUE TITLE
Need to add permissions to write in vendor folder before can run this

### ISSUE THREAD

**Issue by LegolasGChief** [ArqTras/nodejs-pool#13]
Cannot be ran using sudo so need to manually add permissions to write to folder

https://github.com/ArqTras/nodejs-pool/blob/a5cf470e5c11296699942d157b6a213aec99432f/deployment/deploy_aeon.bash#L48

**Comment by ArqTras** [comment]
On wiki there is info about add user to sudoers its important one

**Comment by LegolasGChief** [comment]
Yes I have done that
