### ISSUE TITLE
Network hash not valid

### ISSUE THREAD

**Issue by dodolboks** [ArqTras/nodejs-pool#14]
Hallo, i try build ETN pool from your repo but network hasrate seem invalid.

This my pool http://byur.in/

Thanks

**Comment by ArqTras** [comment]
Go to poolui dir than utils and find file called stings.js 
In the end of line:
return Math.floor(hashrate / 60)
It should solved Your problem 
Pool ui is developed by miziel

**Comment by dodolboks** [comment]
Thanks for your respon, i think is not crrect becouse pool worker not working.  

 pool > 2018-02-15 21:28 +00:00: TypeError: Cannot read property 'height' of undefined                 │
│[ 1] pm2-logrotate         Mem:  44 MB     ││ pool >     at Timeout._onTimeout (/home/pooldaemon/nodejs-pool/lib/pool.js:819:114)                   │
│[ 7] pool     Mem:  63 MB    CPU:  1 %  on ││ pool >     at ontimeout (timers.js:365:14)                                                            │
│[ 5] remoteShare     Mem:  53 MB    CPU:   ││ pool >     at tryOnTimeout (timers.js:237:5)                                                          │
│[ 3] worker     Mem:  59 MB    CPU:  0 %   ││ pool >     at Timer.listOnTimeout (timers.js:207:5)                                                   │
│                                           ││ PM2 > App [pool] with id [7] and pid [18182], exited with code [1] via signal [SIGINT]                │
│                                           ││ PM2 > Starting execution sequence in -fork mode- for app name:pool id:7                               │
│                                           ││ PM2 > App name:pool id:7 online                                                                       │
│                                           ││ pool > 2018-02-15 21:28 +00:00: Master cluster setting up 2 workers...                                │
│                                           ││ pool > 2018-02-15 21:28 +00:00: Did not send e-mail successfully!  Response: undefined Response:      │
│                                           ││ undefined


Can you advice me what wrong withmy pool ?

Thanks

**Comment by ArqTras** [comment]
Join discord and pm me : https://discord.gg/fF6McGB
I think your electroneumd is not full sync, modules didn't start (they sould be runned after full sync)
