### ISSUE TITLE
Another install problem

### ISSUE THREAD

**Issue by lewpio** [ArqTras/nodejs-pool#2]
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for resolvconf (1.78ubuntu6) ...
Processing triggers for ca-certificates (20170717~16.04.1) ...
Updating certificates in /etc/ssl/certs...
17 added, 42 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
bash: line 20: unexpected EOF while looking for matching `"'
bash: line 21: syntax error: unexpected end of file

**Comment by lewpio** [comment]
And another.
After installing from script still no access for pool@localhost.
Seems sql is not executed and database not created.

**Comment by ArqTras** [comment]
Do you have sudouser inserted in to /etc/sudoers

**Comment by lewpio** [comment]
Yes.

Tried both run via curl and from git clone - same issues.

**Comment by ArqTras** [comment]
Take a look at last commit to deploy_electroneum I make mistake with base.sql -> baseetn.sql 
Also if you decide to run etn pool update electroneum daemon due to last issue of blockchain
