### ISSUE TITLE
Are these coins all working?

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [ArqTras/nodejs-pool#3]
How can I contribute if not?

**Comment by ArqTras** [comment]
As you see there is no full ready deployment with base sql files.
Working from deploy bash : aeon , etn, graft, sumo (with some daemon and wallet issues but this is coin dev) already testing intense. All other need to be developed by hand so you need to know base sql and daemon installation + base nodejs installation or create own deployment file If you have some info and You wish to share feel free to send info support@supportaeon.com also telegram ArqTras

**Comment by ArqTras** [comment]
Some of coins need forknote-utils and many changes in code. ITNS not work with my pool code. It is not repository clone and run but few of them work nice. https://supportcryptonight.com 
I can confirm that aeon, etn, graft and stellite works well, with ipbc and alloy need many changes intense is not supported other not check
Not all coins files collected are verified
