### ISSUE TITLE
Null and leaked fee addresses in mysql

### ISSUE THREAD

**Issue by bobbieltd** [ArqTras/nodejs-pool#3]
SELECT * FROM pool.balance;

For ETN pool : 
|  1 | 2017-12-27 13:58:21 | etnk1ELUj9c85xLf6LKw86F2GP7kkixgncZMyYNErDKh4TyRU6BnA3USsFGj1r8wSPRAJcr61cShh8TAVgWA5Yi39UtV8b1vW1 | NULL       | fees      |       0 |      0 |
|  2 | 2017-12-27 13:58:21 |                                                                                                    | NULL       | fees      |       0 |      0 |
|  3 | 2017-12-27 13:58:21 | etnkDsYP3BFCKygekcUeiF1oCmYfkp9HYXdtmiEp1ttWSbPDDnnZ6uMSw18WpURARUYe5AY3x3JGKT2dFvTJEPrM59X1mgdCiX | NULL       | fees      |       0 |      0 |
Notice : the 2nd row is emtpy address. Who do I contribute to 3rd row ? You or 3ditguy ?

For AEON pool : 
|  1 | 2017-12-26 17:13:30 | WmtcP4NHXD2fhvvYnQCBSf3U255gxj9At3gpX9ivArRQaqgq9Mz1oRK7HSYd8tqbBZEW59AiadvULB8kD5Br5roK2aQY1JmsW | NULL       | fees      |       0 |      0 |
|  2 | 2017-12-26 17:13:30 | 44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A   | NULL       | fees      |       0 |      0 |
|  3 | 2017-12-26 17:13:30 | 44Ldv5GQQhP7K7t3ZBdZjkPA7Kg7dhHwk3ZM3RJqxxrecENSFx27Vq14NAMAd2HBvwEPUVVvydPRLcC69JCZDHLT2X5a4gr   | NULL       | fees      |       0 |      0 |
|  4 | 2017-12-26 19:11:42 | WmsSWgtT1JPg5e3cK41hKXSHVpKW7e47bjgiKmWZkYrhSS5LhRemNyqayaSBtAQ6517eo5PtH9wxHVmM78JDZSUu2W8PqRiNs | NULL       | fees      |       0 |      0 |
|  5 | 2017-12-26 19:11:42 | WmtvM6SoYya4qzkoPB4wX7FACWcXyFPWAYzfz7CADECgKyBemAeb3dVb3QomHjRWwGS3VYzMJAnBXfUx5CfGLFZd1U7ssdXTu | NULL       | fees      |       0 |      0 |

How can the XMR addresses of Snipa and core Developers sneaked into databases ? 

Could you help me ?

**Comment by bobbieltd** [comment]
I just change some things at port config. Nothing happens without restarting pool and api. For the ports’ name fix. Not sure if it’s enough.

**Comment by ArqTras** [comment]
Beta info
https://github.com/ArqTras/nodejs-pool/wiki

**Comment by FurianXO** [comment]
I'm curious, we are using this as a private pool (solo mining with 43 miners), if we do not setup the wallet, and only use the pool address, how does that work?

**Comment by bobbieltd** [comment]
@FurianXO You need dual wallets ( one pool wallet and one fee wallet ). If you use for private mining, you ca put two or three fee parameters in mysql to 0.
