### ISSUE TITLE
Sumocoin Pool Error

### ISSUE THREAD

**Issue by CoFix** [ArqTras/nodejs-pool#8]
I am getting this error

/home/sumo/.pm2/logs/pool-out-7.log last 15 lines:
/home/sumo/.pm2/logs/pool-error-7.log last 15 lines:
7|pool     |     at processImmediate [as _immediateCallback] (timers.js:722:5)
7|pool     | 2018-04-12 08:08 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
7|pool     | TypeError: Cannot read property 'funcFile' of undefined
7|pool     |     at /home/sumo/nodejs-pool/init.js:46:42
7|pool     |     at tryCatcher (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
7|pool     |     at Promise._settlePromiseFromHandler (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
7|pool     |     at Promise._settlePromise (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
7|pool     |     at Promise._settlePromise0 (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
7|pool     |     at Promise._settlePromises (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
7|pool     |     at Async._drainQueue (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
7|pool     |     at Async._drainQueues (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
7|pool     |     at Immediate.Async.drainQueues (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
7|pool     |     at runCallback (timers.js:789:20)
7|pool     |     at tryOnImmediate (timers.js:751:5)
7|pool     |     at processImmediate [as _immediateCallback] (timers.js:722:5)

How can i fix it?

Thanks.

**Comment by ArqTras** [comment]
Sumo isnt updated for a long time
