### ISSUE TITLE
Question about AEON and low balances for PPLNS

### ISSUE THREAD

**Issue by devopsralf** [ArqTras/nodejs-pool#8]
Hi, my balances seem low when using AEON. Is this something you have run into? We found three blocks and our pool wallet has all the funds, but its not paying the miners correctly.

**Comment by ArqTras** [comment]
Join discord channel https://discordapp.com/invite/vGeRWQF
Also many depend of effort 
And you can run pm2 gracefulReload payments to be sure that payments go
After few blocks amount is ok

**Comment by ArqTras** [comment]
let amountToPay = Math.floor((shareData.shares / (blockDiff*global.config.pplns.shareMulti)) * rewardTotal);
blockManager.js ^^
this is the problem line Snippa divides by global.config.pplns.shareMulti here
and if there are less than global.config.pplns.shareMulti*blockDiff shares you get this problem
as not all block reward is distributed
so you need to wait few more blocks to get full pplns window

**Comment by ArqTras** [comment]
There is correction on master for blockManager.js
