### ISSUE TITLE
Boolean argument in grf.js

### ISSUE THREAD

**Issue by ImhotepW** [ArqTras/nodejs-pool#9]
Getting following error in lib/coins/grf.js

> Error: Argument 2 should be a boolean
>     at Coin.cryptoNight (/home/pooldaemon/nodejs-pool/lib/coins/grf.js:158:29)

**Comment by ArqTras** [comment]
Looks like bad wallet address for fee

**Comment by ImhotepW** [comment]
Nope, the issue was with multi-hashing module, had to update it as well to make it work.
