### ISSUE TITLE
admin panel issue

### ISSUE THREAD

**Issue by alexmateescu** [ArqTras/nodejs-pool#9]
i am trying to adapt this pool to a new coin but so far i got stuck at the admin part. no matter what username and password i put in is telling me to check the login details. 

i've looked at the db and everything looks fine with the user and the password but it won't work.

**Comment by ArqTras** [comment]
If you have correct api address in poolui globals.js
than 
https://github.com/ArqTras/nodejs-pool#final-manual-steps

**Comment by alexmateescu** [comment]
tried that and did not work

regards

**Comment by alexmateescu** [comment]
it looks like my hypervisor is not passing the AES-NI to the vm's

this might be the issue

**Comment by ArqTras** [comment]
If your system doesn't have AES-NI, then it will throw an error during the node-multi-hashing install, as this requires AES-NI. If this is the case, go ahead and change the following line: "multi-hashing": "git+https://github.com/Snipa22/node-multi-hashing-aesni.git", to: "multi-hashing": "git://github.com/clintar/node-multi-hashing.git#Nan-2.0",

In your packages.json, do a npm install, and it should pass.

**Comment by alexmateescu** [comment]
just so other people know there is one more place that needs to be edited:

mysql> select * from pools;
+----+---------+---------------------+--------+---------+-------------+--------------+
| id | ip      | last_checkin        | active | blockID | blockIDTime |
hostname     |
+----+---------+---------------------+--------+---------+-------------+--------------+
|  0 | 0.0.0.0 | 2018-01-26 12:36:51 |      1 |    NULL | NULL        |
testpool.com |
+----+---------+---------------------+--------+---------+-------------+--------------+
1 row in set (0.00 sec)

mysql> update pool.pools set hostname='your pool dns or ip here ' where
id=0;

after this the admin page is loading:

**Comment by ArqTras** [comment]
In first run this config get from your file where you save config_example with need to be changed to config.json and have values as you need.
It must be configured before you run daemons
